version: '3.1'

services:
  node:
    image: node:10
    working_dir: /app
    depends_on:
      - db
    environment:
      NODE_ENV: development
    volumes:
      - ./:/app
    ports:
      - ${PORT}:${PORT}
    command: npm run dev

  db:
    image: mysql:5.7
    restart: always
    container_name: opensesame_db
    volumes:
      - ./sqldump:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
